// Domain data: robot categories, robot catalog, industries, ecosystem, timeline.

export type Category = {
  slug: string;
  title: string;
  blurb: string;
  items: string[];
};

export const categories: Category[] = [
  {
    slug: "service",
    title: "Service Robots",
    blurb: "Reception, concierge, delivery, cleaning and security for public spaces.",
    items: ["Hotels", "Hospitals", "Airports", "Restaurants", "Malls", "Banks", "Reception", "Concierge", "Delivery", "Cleaning", "Security"],
  },
  {
    slug: "retail",
    title: "Retail Robots",
    blurb: "Cashier, inventory, shelf-scanning and shopping assistants for stores.",
    items: ["Cashier", "Inventory", "Shelf scanning", "Customer assist", "Price checking", "Self checkout", "Store analytics"],
  },
  {
    slug: "restaurant",
    title: "Restaurant Robots",
    blurb: "Food delivery, kitchen automation, barista and dish-collection robots.",
    items: ["Food delivery", "Kitchen automation", "Cooking", "Drinks", "Coffee", "Table assist", "Dish collection"],
  },
  {
    slug: "healthcare",
    title: "Healthcare Robots",
    blurb: "Patient monitoring, medication logistics, surgery assist and elderly care.",
    items: ["Patient monitoring", "Medication delivery", "Surgery assist", "Hospital logistics", "Telemedicine", "Elderly care", "Rehabilitation", "Emergency response"],
  },
  {
    slug: "hotel",
    title: "Hotel Robots",
    blurb: "Room delivery, reception, luggage handling and smart concierge.",
    items: ["Room delivery", "Reception", "Cleaning", "Luggage", "Guest assistant", "Smart concierge", "Security"],
  },
  {
    slug: "education",
    title: "Education Robots",
    blurb: "Teaching assistants, coding companions and AI laboratory robots.",
    items: ["Learning", "Teaching assistants", "Coding", "Research", "AI labs", "Campus"],
  },
  {
    slug: "home",
    title: "Home Robots",
    blurb: "Cleaning, cooking, companion, security and garden robots for the home.",
    items: ["Smart assistants", "Cleaning", "Cooking", "Companion", "Security", "Gardening", "Pet care", "Laundry"],
  },
  {
    slug: "industrial",
    title: "Industrial Robots",
    blurb: "Assembly, packaging, sorting, inspection and warehouse automation.",
    items: ["Assembly", "Packaging", "Sorting", "Material handling", "Inspection", "Quality control", "Warehouse", "Palletizing", "Logistics"],
  },
  {
    slug: "construction",
    title: "Construction Robots",
    blurb: "Bricklaying, painting, surveying, inspection and heavy lifting.",
    items: ["Bricklaying", "Painting", "Road construction", "Surveying", "Inspection", "Mining", "Heavy lifting"],
  },
  {
    slug: "agriculture",
    title: "Agriculture Robots",
    blurb: "Harvesting, planting, weeding, spraying and farm monitoring.",
    items: ["Harvesting", "Planting", "Weeding", "Spraying", "Livestock", "Drone integration", "Farm monitoring"],
  },
  {
    slug: "manufacturing",
    title: "Manufacturing Robots",
    blurb: "CNC automation, welding, assembly, machine tending and inspection.",
    items: ["CNC automation", "Welding", "Assembly", "Inspection", "Packaging", "Machine tending"],
  },
  {
    slug: "warehouse",
    title: "Warehouse Robots",
    blurb: "Picking, sorting, inventory, transport, loading and unloading.",
    items: ["Picking", "Sorting", "Inventory", "Transport", "Loading", "Unloading", "Automation"],
  },
  {
    slug: "security",
    title: "Security Robots",
    blurb: "Patrol, guard, border surveillance, monitoring and threat detection.",
    items: ["Patrol", "Guard", "Border surveillance", "Monitoring", "Threat detection"],
  },
  {
    slug: "defence",
    title: "Military & Defence",
    blurb: "Reconnaissance, bomb disposal, drone systems and battlefield AI.",
    items: ["Ground combat", "Reconnaissance", "Bomb disposal", "Drone systems", "Autonomous vehicles", "Surveillance", "Rescue", "Defense AI"],
  },
  {
    slug: "marine",
    title: "Marine Robotics",
    blurb: "Underwater inspection, research, ports and shipping automation.",
    items: ["Underwater", "Inspection", "Research", "Ports", "Shipping"],
  },
  {
    slug: "space",
    title: "Space Robotics",
    blurb: "Satellite servicing, exploration, maintenance and research.",
    items: ["Satellite robots", "Exploration", "Maintenance", "Research"],
  },
  {
    slug: "entertainment",
    title: "Entertainment Robots",
    blurb: "Theme parks, museums, events and interactive experiences.",
    items: ["Theme parks", "Museums", "Events", "Shows", "Interactive"],
  },
  {
    slug: "smart-city",
    title: "Smart City Robotics",
    blurb: "Traffic, cleaning, infrastructure inspection and public safety.",
    items: ["Traffic management", "Cleaning", "Inspection", "Delivery", "Public safety", "Maintenance"],
  },
];

export type Robot = {
  slug: string;
  name: string;
  series: string; // shop category, e.g. "Humanoid"
  category: string; // same as series, kept for back-compat
  tagline: string;
  description: string[]; // long-form paragraphs
  priceFrom: number;
  price: number;
  status: "Available" | "Pre-order" | "Coming Soon";
  badge?: string; // e.g. "Best seller", "New"
  rating: number;
  reviews: number;
  accent: string; // hex
  image: string; // primary product image
  gallery: string[]; // image paths incl. primary
  highlights: string[]; // short selling points
  functionality: { title: string; desc: string }[]; // what it does
  specs: { label: string; value: string }[];
  features: string[]; // quick capability chips
  whatsInBox: string[];
  useCases: string[];
};

export const robots: Robot[] = [
  {
    slug: "atlas-one",
    name: "NETICS Atlas One",
    series: "Humanoid",
    category: "Humanoid",
    tagline: "A general-purpose humanoid that walks, talks, sees and learns.",
    description: [
      "Atlas One is our flagship general-purpose humanoid — a 1.72m bipedal robot engineered to work alongside people in the real world. It walks, balances, manipulates objects and holds natural conversations, all powered on-device by the NETICS Brain X2 compute module.",
      "With 42 degrees of freedom and full-body force sensing, Atlas One can lift, carry, sort and assemble with human-like dexterity. Its 360° depth-and-RGB vision system builds a live 3D map of its surroundings, while emotion-aware voice AI lets it greet, guide and assist customers, patients and staff in 40+ languages.",
      "Every Atlas One ships connected to NETICS Cloud for fleet management, over-the-air skill updates and shared learning — so your robot keeps getting smarter long after it arrives.",
    ],
    priceFrom: 89000,
    price: 89000,
    status: "Pre-order",
    badge: "Flagship",
    rating: 4.9,
    reviews: 128,
    accent: "#19e3ff",
    image: "/robots/atlas-hero.jpg",
    gallery: ["/robots/atlas-hero.jpg", "/robots/humanoid-black.jpg", "/robots/hand.jpg", "/robots/circuit.jpg"],
    highlights: [
      "Full bipedal walking & balance on uneven terrain",
      "42 DOF with human-like grasping and manipulation",
      "Emotion-aware voice AI in 40+ languages",
      "On-device NETICS Brain X2 — private by design",
    ],
    functionality: [
      { title: "Walks & balances", desc: "Dynamic bipedal locomotion across stairs, ramps and uneven floors with real-time stability control." },
      { title: "Sees in 3D", desc: "360° depth + RGB perception builds a live map for navigation, obstacle avoidance and object recognition." },
      { title: "Manipulates objects", desc: "Two dexterous hands with force feedback lift, carry, sort and assemble up to 25kg payload." },
      { title: "Talks naturally", desc: "Conversational, emotion-aware voice assistant that understands and replies in 40+ languages." },
      { title: "Learns continuously", desc: "Cloud-synced memory and OTA skill packs mean capabilities expand over time." },
      { title: "Recognises people", desc: "Facial and gesture recognition for personalised, secure interactions." },
    ],
    specs: [
      { label: "Height", value: "1.72 m" },
      { label: "Weight", value: "62 kg" },
      { label: "Payload", value: "25 kg" },
      { label: "Runtime", value: "8 hrs" },
      { label: "Degrees of Freedom", value: "42" },
      { label: "Vision", value: "360° depth + RGB" },
      { label: "Compute", value: "NETICS Brain X2" },
      { label: "Connectivity", value: "5G · Wi-Fi 6E" },
    ],
    features: ["Bipedal walking", "Emotion AI", "Multilingual voice", "Object manipulation", "Cloud sync memory", "Facial recognition"],
    whatsInBox: ["Atlas One humanoid robot", "Fast-charging dock", "Spare battery pack", "NETICS OS licence (1 yr)", "Quick-start guide", "On-site commissioning"],
    useCases: ["Reception & concierge", "Retail assistance", "Healthcare support", "Logistics & sorting", "Education & research"],
  },
  {
    slug: "aria-r1",
    name: "NETICS Aria R1",
    series: "Service",
    category: "Service",
    tagline: "A friendly reception & concierge humanoid for any front desk.",
    description: [
      "Aria R1 is the face of modern customer service — an expressive service humanoid built to greet, guide and assist guests in hotels, hospitals, airports, banks and malls. Its warm design and big animated eyes put people instantly at ease.",
      "Aria recognises returning guests, answers questions on a built-in touch display, books appointments, prints tickets and escorts visitors to the right place. A natural multilingual voice means every guest is understood, whatever language they speak.",
      "Wall-powered or battery, Aria runs all day and integrates with your booking, ticketing and CRM systems out of the box.",
    ],
    priceFrom: 34500,
    price: 34500,
    status: "Available",
    badge: "Best seller",
    rating: 4.8,
    reviews: 214,
    accent: "#7c5cff",
    image: "/robots/pepper.jpg",
    gallery: ["/robots/pepper.jpg", "/robots/hand.jpg", "/robots/circuit.jpg"],
    highlights: [
      "Warm, expressive face that welcomes every guest",
      "Recognises returning visitors and personalises service",
      "Built-in touch display for bookings & info",
      "Natural conversation in 30+ languages",
    ],
    functionality: [
      { title: "Greets guests", desc: "Detects approaching visitors and welcomes them by name where recognised." },
      { title: "Answers questions", desc: "Voice + touchscreen Q&A trained on your venue, services and FAQs." },
      { title: "Guides & escorts", desc: "Points or leads visitors to rooms, gates, desks and facilities." },
      { title: "Handles bookings", desc: "Check-ins, appointments and ticketing through integrated systems." },
      { title: "Speaks every language", desc: "Real-time multilingual conversation for international guests." },
    ],
    specs: [
      { label: "Height", value: "1.20 m" },
      { label: "Weight", value: "28 kg" },
      { label: "Runtime", value: "12 hrs" },
      { label: "Display", value: '10.1" touch' },
      { label: "Voice", value: "Natural · 30+ langs" },
      { label: "Vision", value: "Face + gesture" },
      { label: "Connectivity", value: "Wi-Fi 6 · LTE" },
      { label: "Movement", value: "Omni-wheel base" },
    ],
    features: ["Guest greeting", "Face recognition", "Touch display", "Multilingual voice", "Bookings", "CRM integration"],
    whatsInBox: ["Aria R1 service robot", "Charging dock", "Floor mat", "NETICS OS licence (1 yr)", "Setup & branding kit"],
    useCases: ["Hotel reception", "Hospital wayfinding", "Airport information", "Bank concierge", "Retail greeter"],
  },
  {
    slug: "nova-x1",
    name: "NETICS Nova X1",
    series: "Humanoid",
    category: "Humanoid",
    tagline: "An autonomous humanoid worker for repetitive and risky tasks.",
    description: [
      "Nova X1 is a rugged humanoid built for work most people would rather not do — repetitive line tasks, machine tending, material handling and operations in hazardous zones. Its all-metal frame and sealed joints stand up to dust, heat and round-the-clock duty.",
      "Nova learns a task by demonstration: guide it once and it repeats with sub-millimetre consistency. Swappable end-effectors let the same robot pick, place, screw, scan and pack across a shift.",
      "Deployed as a fleet, Nova units coordinate through NETICS Cloud to share skills and balance workload automatically.",
    ],
    priceFrom: 62000,
    price: 62000,
    status: "Pre-order",
    badge: "New",
    rating: 4.7,
    reviews: 76,
    accent: "#2f6bff",
    image: "/robots/humanoid-black.jpg",
    gallery: ["/robots/humanoid-black.jpg", "/robots/factory.jpg", "/robots/hand.jpg"],
    highlights: [
      "Learns tasks by demonstration in minutes",
      "Swappable end-effectors for any job",
      "Rugged, sealed build for 24/7 duty",
      "Fleet-coordinated through NETICS Cloud",
    ],
    functionality: [
      { title: "Tends machines", desc: "Loads, unloads and operates CNC, presses and packaging lines autonomously." },
      { title: "Handles materials", desc: "Moves, sorts and stacks parts and boxes across the workcell." },
      { title: "Learns by showing", desc: "Demonstrate a task once; Nova repeats it with high precision." },
      { title: "Works in hazard zones", desc: "Operates safely where heat, dust or fumes make human work risky." },
      { title: "Swaps tools", desc: "Quick-change grippers, screwdrivers and scanners for multi-step jobs." },
    ],
    specs: [
      { label: "Height", value: "1.75 m" },
      { label: "Weight", value: "78 kg" },
      { label: "Payload", value: "30 kg" },
      { label: "Runtime", value: "10 hrs / hot-swap" },
      { label: "Repeatability", value: "±0.1 mm" },
      { label: "Rating", value: "IP54" },
      { label: "Compute", value: "NETICS Brain X1" },
      { label: "Safety", value: "Collaborative" },
    ],
    features: ["Machine tending", "Material handling", "Learn by demo", "Tool changer", "Fleet sync", "Hazard-rated"],
    whatsInBox: ["Nova X1 humanoid worker", "Charging station", "2× end-effectors", "Safety scanner kit", "NETICS OS licence (1 yr)"],
    useCases: ["Factory lines", "Warehouse handling", "Machine tending", "Hazardous operations", "Packaging"],
  },
  {
    slug: "forge-f9",
    name: "NETICS Forge F9",
    series: "Industrial",
    category: "Industrial",
    tagline: "A 6-axis industrial arm for welding, assembly and machine tending.",
    description: [
      "Forge F9 is a precision 6-axis robotic arm engineered for the factory floor. With a 1.8m reach, 60kg payload and ±0.02mm repeatability, it welds, assembles, picks and tends machines faster and more consistently than any manual process.",
      "Vision-guided picking and force feedback let Forge handle parts of varying position and fragility, while its digital twin lets you program and simulate offline before a single cable is plugged in.",
      "Collaborative safety means Forge works safely beside your team, no cage required.",
    ],
    priceFrom: 31000,
    price: 31000,
    status: "Available",
    rating: 4.9,
    reviews: 187,
    accent: "#19e3ff",
    image: "/robots/factory.jpg",
    gallery: ["/robots/factory.jpg", "/robots/hand.jpg", "/robots/printer.jpg"],
    highlights: [
      "±0.02mm repeatability for precision work",
      "Vision-guided picking with force feedback",
      "Offline programming via digital twin",
      "Collaborative — safe beside people",
    ],
    functionality: [
      { title: "Welds & assembles", desc: "Consistent, high-speed welding and assembly across long production runs." },
      { title: "Picks with vision", desc: "Camera-guided picking adapts to part position, shape and orientation." },
      { title: "Tends machines", desc: "Loads and unloads CNC, injection and packaging equipment around the clock." },
      { title: "Simulates offline", desc: "Program and validate in the digital twin before deploying to the line." },
      { title: "Predicts maintenance", desc: "On-board sensors flag wear before it causes downtime." },
    ],
    specs: [
      { label: "Reach", value: "1.8 m" },
      { label: "Payload", value: "60 kg" },
      { label: "Repeatability", value: "±0.02 mm" },
      { label: "Axes", value: "6" },
      { label: "Cycle time", value: "0.4 s" },
      { label: "Mounting", value: "Floor · ceiling" },
      { label: "Safety", value: "Collaborative" },
      { label: "Control", value: "NETICS OS" },
    ],
    features: ["Vision-guided picking", "Force feedback", "Digital twin", "Predictive maintenance", "Tool changer", "Offline programming"],
    whatsInBox: ["Forge F9 arm", "Controller cabinet", "Teach pendant", "Mounting plate", "Starter gripper", "NETICS OS licence (1 yr)"],
    useCases: ["Welding", "Assembly", "Machine tending", "Pick & place", "Quality inspection"],
  },
  {
    slug: "sentinel-s4",
    name: "NETICS Sentinel S4",
    series: "Security",
    category: "Security",
    tagline: "An autonomous security robot that patrols and detects threats 24/7.",
    description: [
      "Sentinel S4 patrols your perimeter so your team doesn't have to. Combining LiDAR, thermal and RGB vision, it autonomously navigates sites day and night, detecting intruders, fire, and anomalies before they become incidents.",
      "When Sentinel spots something, it streams live video to your control room, challenges intruders through two-way audio, and logs every event. Its all-weather IP67 body and 16-hour runtime keep watch through any conditions, recharging itself between rounds.",
      "License-plate recognition, restricted-zone alerts and integration with existing CCTV make Sentinel a force-multiplier for any security operation.",
    ],
    priceFrom: 42000,
    price: 42000,
    status: "Available",
    rating: 4.7,
    reviews: 95,
    accent: "#2f6bff",
    image: "/robots/surveil.jpg",
    gallery: ["/robots/surveil.jpg", "/robots/drone.jpg", "/robots/circuit.jpg"],
    highlights: [
      "Autonomous day & night patrols",
      "Thermal + LiDAR + RGB threat detection",
      "Live streaming with two-way audio",
      "All-weather IP67, self-charging",
    ],
    functionality: [
      { title: "Patrols autonomously", desc: "Runs scheduled or random routes across your site without an operator." },
      { title: "Detects threats", desc: "Thermal and vision AI spot intruders, fire and anomalies in real time." },
      { title: "Streams & alerts", desc: "Pushes live video and instant alerts to your control room and phones." },
      { title: "Reads plates", desc: "License-plate recognition for vehicle access and watch-lists." },
      { title: "Challenges intruders", desc: "Two-way audio lets operators speak through the robot on the spot." },
    ],
    specs: [
      { label: "Speed", value: "12 km/h" },
      { label: "Runtime", value: "16 hrs" },
      { label: "Thermal range", value: "200 m" },
      { label: "Sensors", value: "LiDAR · Thermal · RGB" },
      { label: "Rating", value: "IP67" },
      { label: "Comms", value: "5G · Mesh" },
      { label: "Charging", value: "Auto-dock" },
      { label: "Storage", value: "1 TB on-board" },
    ],
    features: ["24/7 patrol", "Thermal detection", "License plate AI", "Two-way audio", "Auto-charging", "Incident streaming"],
    whatsInBox: ["Sentinel S4 robot", "Weatherproof charging dock", "Control-room software", "Mounting hardware", "NETICS OS licence (1 yr)"],
    useCases: ["Perimeter security", "Warehouse patrol", "Campus safety", "Parking & access", "Critical infrastructure"],
  },
  {
    slug: "skyeye-d2",
    name: "NETICS SkyEye D2",
    series: "Aerial",
    category: "Aerial",
    tagline: "A surveillance & mapping drone with autonomous flight and AI vision.",
    description: [
      "SkyEye D2 takes your operations into the air. This autonomous drone flies pre-planned or AI-guided missions to inspect, survey and map sites in a fraction of the time of ground crews.",
      "A stabilised 4K camera with optional thermal payload feeds real-time AI that detects defects, counts assets and flags hazards. SkyEye returns home and recharges on its own, ready for the next flight.",
      "From construction progress to crop health to security overwatch, SkyEye gives you a live eye in the sky — controlled from the same NETICS dashboard as the rest of your fleet.",
    ],
    priceFrom: 12800,
    price: 12800,
    status: "Available",
    badge: "Popular",
    rating: 4.6,
    reviews: 142,
    accent: "#19e3ff",
    image: "/robots/drone.jpg",
    gallery: ["/robots/drone.jpg", "/robots/drone2.jpg", "/robots/circuit.jpg"],
    highlights: [
      "Autonomous pre-planned & AI-guided flights",
      "Stabilised 4K + optional thermal camera",
      "Real-time AI detection and mapping",
      "Auto return-to-home and recharge",
    ],
    functionality: [
      { title: "Flies missions", desc: "Executes autonomous waypoint or AI-guided survey routes." },
      { title: "Inspects & maps", desc: "Captures 4K imagery to build orthomaps, 3D models and inspection reports." },
      { title: "Detects in real time", desc: "On-board AI flags defects, hazards and changes as it flies." },
      { title: "Sees heat", desc: "Optional thermal payload for search, energy and security work." },
      { title: "Returns safely", desc: "Geofencing, obstacle avoidance and auto return-to-home." },
    ],
    specs: [
      { label: "Flight time", value: "42 min" },
      { label: "Range", value: "8 km" },
      { label: "Top speed", value: "72 km/h" },
      { label: "Camera", value: "4K stabilised" },
      { label: "Payload", value: "Thermal (opt)" },
      { label: "Wind rating", value: "12 m/s" },
      { label: "Comms", value: "Encrypted 5G" },
      { label: "Charging", value: "Auto pad" },
    ],
    features: ["Autonomous flight", "4K imaging", "Thermal option", "AI detection", "Mapping & 3D", "Auto-recharge"],
    whatsInBox: ["SkyEye D2 drone", "Auto-charging landing pad", "2× batteries", "Controller", "Mapping software", "Carry case"],
    useCases: ["Site survey & mapping", "Construction progress", "Crop monitoring", "Security overwatch", "Infrastructure inspection"],
  },
  {
    slug: "harvest-h3",
    name: "NETICS Harvest H3",
    series: "Agriculture",
    category: "Agriculture",
    tagline: "An autonomous field robot for harvesting, spraying and monitoring.",
    description: [
      "Harvest H3 brings precision robotics to the farm. This rugged autonomous rover navigates rows on its own to harvest selectively, spray exactly where needed and monitor crop health across the season.",
      "Crop-health AI inspects every plant, targeting weeds and pests while cutting chemical use by up to 80%. RTK GPS keeps it accurate to ±2cm, and swappable tool modules turn one machine into a whole season's worth of equipment.",
      "Solar-assisted power and all-weather build mean Harvest works long days and links directly to SkyEye drones for full farm coverage.",
    ],
    priceFrom: 27500,
    price: 27500,
    status: "Pre-order",
    rating: 4.5,
    reviews: 58,
    accent: "#2f6bff",
    image: "/robots/drone2.jpg",
    gallery: ["/robots/drone2.jpg", "/robots/drone.jpg", "/robots/sketch.jpg"],
    highlights: [
      "Selective AI harvesting & targeted spraying",
      "Cuts chemical use by up to 80%",
      "RTK GPS accurate to ±2cm",
      "Swappable tool modules, solar-assisted",
    ],
    functionality: [
      { title: "Harvests selectively", desc: "Identifies ripe produce and picks only what's ready, reducing waste." },
      { title: "Sprays precisely", desc: "Targets weeds and pests plant-by-plant to slash chemical use." },
      { title: "Monitors crops", desc: "Crop-health AI maps yield, stress and disease across the field." },
      { title: "Navigates rows", desc: "RTK GPS + vision follow rows autonomously to ±2cm." },
      { title: "Adapts with modules", desc: "Swap tools for harvesting, weeding, seeding and spraying." },
    ],
    specs: [
      { label: "Coverage", value: "40 ha/day" },
      { label: "Runtime", value: "10 hrs (solar+)" },
      { label: "Drive", value: "4WD electric" },
      { label: "Precision", value: "RTK GPS ±2 cm" },
      { label: "Vision", value: "Crop-health AI" },
      { label: "Modules", value: "Swappable" },
      { label: "Rating", value: "IP66" },
      { label: "Link", value: "Drone-integrated" },
    ],
    features: ["Selective harvesting", "Targeted spraying", "Weed detection", "Yield mapping", "Drone link", "All-weather"],
    whatsInBox: ["Harvest H3 rover", "Charging station", "Harvest + spray modules", "RTK base station", "Farm dashboard licence"],
    useCases: ["Selective harvesting", "Precision spraying", "Weeding", "Crop monitoring", "Yield mapping"],
  },
  {
    slug: "helix-h1",
    name: "NETICS Helix H1",
    series: "Industrial",
    category: "Industrial",
    tagline: "A precision robotic hand for delicate, high-dexterity manipulation.",
    description: [
      "Helix H1 is a five-finger robotic hand that brings human-level dexterity to automation. With tactile sensors in every fingertip, it grips eggs without cracking them and torque-tightens bolts without slipping.",
      "Mount Helix on a Forge arm or a Nova humanoid and unlock tasks that rigid grippers can't touch: assembling electronics, sorting irregular items, handling fragile goods and fine tool use.",
      "Force and slip sensing, plus AI grasp planning, mean Helix figures out how to hold almost anything you hand it.",
    ],
    priceFrom: 24000,
    price: 24000,
    status: "Available",
    rating: 4.8,
    reviews: 64,
    accent: "#7c5cff",
    image: "/robots/hand.jpg",
    gallery: ["/robots/hand.jpg", "/robots/factory.jpg", "/robots/circuit.jpg"],
    highlights: [
      "Five fingers with fingertip tactile sensing",
      "Handles fragile and irregular objects",
      "AI grasp planning for any shape",
      "Mounts on Forge arms & Nova humanoids",
    ],
    functionality: [
      { title: "Grips anything", desc: "AI grasp planning adapts to shape, weight and fragility on the fly." },
      { title: "Senses touch", desc: "Tactile and slip sensors prevent dropping or crushing items." },
      { title: "Assembles fine parts", desc: "Dexterous enough for electronics and small-component assembly." },
      { title: "Uses tools", desc: "Holds and operates hand tools for finishing tasks." },
    ],
    specs: [
      { label: "Fingers", value: "5 · 20 DOF" },
      { label: "Grip force", value: "150 N" },
      { label: "Sensors", value: "Tactile + slip" },
      { label: "Payload", value: "5 kg" },
      { label: "Mount", value: "Universal flange" },
      { label: "Control", value: "NETICS OS" },
      { label: "Repeatability", value: "±0.05 mm" },
      { label: "Weight", value: "1.2 kg" },
    ],
    features: ["Tactile sensing", "AI grasp planning", "Slip detection", "Fine assembly", "Tool use", "Universal mount"],
    whatsInBox: ["Helix H1 hand", "Universal mounting flange", "Cabling kit", "Calibration tool", "SDK licence"],
    useCases: ["Electronics assembly", "Fragile handling", "Irregular sorting", "Lab automation", "Tool operation"],
  },
  {
    slug: "companion-c1",
    name: "NETICS Companion C1",
    series: "Home",
    category: "Home",
    tagline: "A friendly home companion that helps, learns and protects.",
    description: [
      "Companion C1 brings helpful robotics home. This small, friendly assistant controls your smart home, answers questions, makes video calls and keeps an eye on the house when you're away.",
      "Its expressive design is loved by kids and grandparents alike, while on-device AI keeps your family's data private. Companion learns routines, sends reminders and patrols rooms for security at night.",
      "Quiet, safe and always learning, C1 is the easiest way to bring an intelligent helper into everyday life.",
    ],
    priceFrom: 4900,
    price: 4900,
    status: "Pre-order",
    badge: "New",
    rating: 4.6,
    reviews: 311,
    accent: "#19e3ff",
    image: "/robots/walle.jpg",
    gallery: ["/robots/walle.jpg", "/robots/walle2.jpg", "/robots/tin.jpg"],
    highlights: [
      "Controls your whole smart home by voice",
      "Private, on-device family AI",
      "Night-time security patrol",
      "Video calls, reminders & companionship",
    ],
    functionality: [
      { title: "Runs your home", desc: "Voice control for lights, locks, climate and Matter devices." },
      { title: "Keeps watch", desc: "Patrols rooms and alerts you to motion, smoke or open doors." },
      { title: "Stays connected", desc: "Hands-free video calls and messages for the whole family." },
      { title: "Helps & reminds", desc: "Medication, appointment and routine reminders with a friendly nudge." },
      { title: "Learns your routines", desc: "Adapts to your household and gets more helpful over time." },
    ],
    specs: [
      { label: "Height", value: "0.45 m" },
      { label: "Runtime", value: "10 hrs" },
      { label: "Voice", value: "Natural · multilingual" },
      { label: "Vision", value: "Face + gesture" },
      { label: "Connectivity", value: "Wi-Fi 6E · Matter" },
      { label: "Privacy", value: "On-device AI" },
      { label: "Audio", value: "Hi-fi speaker + mics" },
      { label: "Charging", value: "Self-docking" },
    ],
    features: ["Smart home control", "Companion AI", "Security patrol", "Reminders & care", "Video calls", "Child & pet aware"],
    whatsInBox: ["Companion C1 robot", "Charging dock", "Quick-start guide", "12-month NETICS Home plan"],
    useCases: ["Smart home hub", "Elderly care", "Family companion", "Home security", "Kids' learning"],
  },
  {
    slug: "scout-s1",
    name: "NETICS Scout S1",
    series: "Education",
    category: "Education",
    tagline: "A programmable robot for classrooms, makers and developers.",
    description: [
      "Scout S1 is where the next generation of roboticists begin. This compact, durable robot is fully programmable — drag-and-drop blocks for beginners, Python and the NETICS SDK for advanced builders.",
      "Scout drives, senses, speaks and sees, making it the perfect platform to teach coding, AI and robotics hands-on. A thriving curriculum and community mean lessons, projects and challenges are ready to go.",
      "Affordable enough for a whole classroom and powerful enough for serious prototyping, Scout opens the door to robotics for everyone.",
    ],
    priceFrom: 1800,
    price: 1800,
    status: "Available",
    badge: "Best value",
    rating: 4.7,
    reviews: 268,
    accent: "#2f6bff",
    image: "/robots/tin.jpg",
    gallery: ["/robots/tin.jpg", "/robots/circuit.jpg", "/robots/coder.jpg"],
    highlights: [
      "Block coding for beginners, Python for pros",
      "Drives, senses, sees and speaks",
      "Full curriculum & community included",
      "Classroom-affordable, prototype-ready",
    ],
    functionality: [
      { title: "Teaches coding", desc: "From drag-and-drop blocks to real Python with the NETICS SDK." },
      { title: "Drives & senses", desc: "Motors, distance and line sensors for hands-on robotics projects." },
      { title: "Sees & speaks", desc: "Camera and speaker enable vision and voice experiments." },
      { title: "Grows with learners", desc: "Beginner to advanced challenges and a shared project library." },
    ],
    specs: [
      { label: "Size", value: "18 cm" },
      { label: "Runtime", value: "6 hrs" },
      { label: "Compute", value: "Quad-core + NPU" },
      { label: "Sensors", value: "Camera · IMU · ToF" },
      { label: "Coding", value: "Blocks · Python" },
      { label: "Connectivity", value: "Wi-Fi · BLE" },
      { label: "Expansion", value: "GPIO + Grove" },
      { label: "Ages", value: "10+" },
    ],
    features: ["Block & Python coding", "Vision experiments", "Voice projects", "Sensor suite", "Curriculum", "Expandable"],
    whatsInBox: ["Scout S1 robot", "USB-C charger", "Sensor expansion pack", "Curriculum access", "Sticker set"],
    useCases: ["STEM classrooms", "Coding clubs", "University labs", "Maker projects", "Rapid prototyping"],
  },
];

export type ShopCategory = {
  slug: string;
  title: string;
  blurb: string;
  image: string;
};

export const shopCategories: ShopCategory[] = [
  { slug: "Humanoid", title: "Humanoid Robots", blurb: "General-purpose robots that walk, talk and work alongside people.", image: "/robots/atlas-hero.jpg" },
  { slug: "Service", title: "Service Robots", blurb: "Reception, concierge and guest-facing robots for any venue.", image: "/robots/pepper.jpg" },
  { slug: "Industrial", title: "Industrial Robots", blurb: "Arms and manipulators for welding, assembly and machine tending.", image: "/robots/factory.jpg" },
  { slug: "Security", title: "Security Robots", blurb: "Autonomous patrol and threat detection, day and night.", image: "/robots/surveil.jpg" },
  { slug: "Aerial", title: "Aerial Drones", blurb: "Autonomous drones for survey, mapping and overwatch.", image: "/robots/drone.jpg" },
  { slug: "Agriculture", title: "Agriculture Robots", blurb: "Precision field robots for harvesting, spraying and monitoring.", image: "/robots/drone2.jpg" },
  { slug: "Home", title: "Home & Companion", blurb: "Friendly assistants that help and protect your household.", image: "/robots/walle.jpg" },
  { slug: "Education", title: "Education & Dev", blurb: "Programmable robots for classrooms, makers and developers.", image: "/robots/tin.jpg" },
];

export const industries = [
  "Healthcare", "Hospitality", "Education", "Manufacturing", "Government",
  "Construction", "Oil & Gas", "Retail", "Restaurants", "Smart Cities",
  "Mining", "Energy", "Transportation", "Logistics", "Warehousing",
  "Military", "Defense", "Agriculture", "Telecom", "Finance",
  "Homes", "Entertainment",
];

export const whyNetics = [
  { title: "Largest robotics ecosystem in Africa", desc: "An end-to-end network of factories, distributors and support centers." },
  { title: "AI-powered robots", desc: "Every machine runs NETICS Brain — vision, voice and predictive intelligence." },
  { title: "Custom manufacturing", desc: "Configure and build robots tailored to your industry and brand." },
  { title: "Worldwide delivery", desc: "Global logistics with local servicing in 48 countries." },
  { title: "Cloud robotics", desc: "Fleet management, OTA updates and digital twins from NETICS Cloud." },
  { title: "Robotics Operating System", desc: "NETICS OS unifies hardware, software and automation on one platform." },
  { title: "Enterprise deployment", desc: "From a single unit to thousands — deployed, integrated and supported." },
  { title: "24/7 support & training", desc: "Maintenance, training and remote support that never sleeps." },
];

export const ecosystem = [
  { name: "NETICS AI", desc: "The intelligence core powering every product." },
  { name: "NETICS Robotics", desc: "Hardware: humanoid, industrial and service robots." },
  { name: "NETICS Cloud", desc: "Fleet, telemetry and OTA at planetary scale." },
  { name: "NETICS Vision", desc: "Real-time perception, detection and recognition." },
  { name: "NETICS Voice", desc: "Multilingual natural conversation engine." },
  { name: "NETICS Brain", desc: "On-robot reasoning, planning and learning compute." },
  { name: "NETICS Assistant", desc: "Human-facing assistant across every surface." },
  { name: "NETICS OS", desc: "The robotics operating system tying it all together." },
  { name: "NETICS Business AI", desc: "Automation and insight for enterprises." },
  { name: "NETICS Automation", desc: "Workflow orchestration across fleets." },
  { name: "NETICS API", desc: "Programmable access to the whole stack." },
  { name: "NETICS Developer Platform", desc: "Build, simulate and ship robot apps." },
  { name: "NETICS Marketplace", desc: "Robots, apps, skills and accessories." },
  { name: "NETICS Humanoid", desc: "The flagship general-purpose humanoid program." },
  { name: "NETICS Smart Home", desc: "Connected robotics for living spaces." },
  { name: "NETICS Smart Factory", desc: "Lights-out manufacturing intelligence." },
  { name: "NETICS Smart City", desc: "Robotics infrastructure for nations." },
];

export const timeline = [
  { year: "2026", title: "Launch NETICS Robotics", desc: "Africa's robotics manufacturer & marketplace goes live." },
  { year: "2027", title: "AI Marketplace", desc: "Open platform for robots, skills and accessories." },
  { year: "2028", title: "Humanoid Assistant", desc: "General-purpose humanoid ships to enterprise." },
  { year: "2029", title: "Smart Factory", desc: "Fully autonomous lights-out production lines." },
  { year: "2030", title: "Autonomous Logistics", desc: "End-to-end robotic supply chains." },
  { year: "2032", title: "Robot Hospitals", desc: "Robotics-assisted care at national scale." },
  { year: "2035", title: "Robot Cities", desc: "Smart-city robotics infrastructure deployed." },
  { year: "2040", title: "AI Infrastructure", desc: "Continental robotics + AI backbone." },
  { year: "2045", title: "Consumer Humanoids", desc: "Affordable humanoids in everyday homes." },
  { year: "2050", title: "Global Robotics Network", desc: "Interconnected autonomous machine networks." },
  { year: "2055", title: "Civilization Infrastructure", desc: "AI & robotics as the substrate of society." },
];

export const dashboardMetrics = [
  { label: "Robots Online", value: 11842, suffix: "", trend: "+182 today" },
  { label: "Countries Deployed", value: 48, suffix: "", trend: "+2 this quarter" },
  { label: "Tasks Completed", value: 190, suffix: "M", trend: "+4.1M / week" },
  { label: "Fleet Uptime", value: 99.2, suffix: "%", trend: "30-day avg" },
];

export const blogPosts = [
  { slug: "humanoid-2028", title: "Why 2028 is the year of the humanoid", tag: "Future", read: "6 min", excerpt: "General-purpose robots are crossing the cost and capability threshold. Here's the data." },
  { slug: "vision-ai-edge", title: "Running Vision AI on the edge, at scale", tag: "Research", read: "9 min", excerpt: "How NETICS Vision keeps perception under 20ms on-robot." },
  { slug: "robots-africa", title: "Building the world's robots from Africa", tag: "Company", read: "5 min", excerpt: "Talent, manufacturing and ambition — the case for African robotics." },
  { slug: "fleet-ota", title: "Shipping OTA updates to 12,000 robots", tag: "Automation", read: "7 min", excerpt: "The architecture behind safe, staged fleet updates with NETICS Cloud." },
  { slug: "swarm-logistics", title: "Swarm intelligence for warehouse logistics", tag: "Robotics", read: "8 min", excerpt: "Hundreds of robots, one coordinated brain. Inside our swarm planner." },
  { slug: "roi-automation", title: "The real ROI of factory automation", tag: "Industry", read: "6 min", excerpt: "A practical model for payback periods on industrial robotics." },
];
